Numpy help us to do metrix calculation which is written in C++

Python provide wrapper on Numpy to use it in python.

that means we can do matrix calculation in faster manner.

Numpy is 3rd party package created by a college student for college project Travis Oliphant in 2005.

Beacuse it is a third party package we have to install it using pip dependency manage from python.org website.

Numpy is open-source.

It help us to read unstructured(where column heading is not defined) data.

array are of three type:

> scaler array

> vector array

> matrix 

we have to import numpy module and if needed can alise also

In [1]:
import numpy as np

In [5]:
a=np.array([10,20,30])
print(a)
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


# array which contain integer and string


In [11]:
b=np.array([10,20,'krishna'])
print(b)

['10' '20' 'krishna']


In [13]:
c=np.array([1,2,3,4.40])
c

array([1. , 2. , 3. , 4.4])

# array conversion into int

In [39]:
d=np.array([1,2,3,4.40],dtype=np.int32)   # interger conversion of all the data 
d

array([1, 2, 3, 4])

In [40]:
e=np.array([1,2,3,4.40],dtype=np.float32)   # float conversion of all the data
e

array([1. , 2. , 3. , 4.4], dtype=float32)

In [41]:
f=np.array([1,2,3,4.40],dtype=np.string_)
f

array([b'1', b'2', b'3', b'4.4'], dtype='|S3')

In [59]:
[i for i in range(1,10,2)]

[1, 3, 5, 7, 9]

In [63]:
a=np.array(np.zeros(10),dtype=np.int16)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [64]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [66]:
np.ones(10,dtype=np.str_)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [67]:
np.full(10,2, dtype=np.int16)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int16)

In [68]:
np.full(4,1000)

array([1000, 1000, 1000, 1000])

# scaler, vector, matrix

In [78]:
a=np.array(10)   # this is called scaler 
print(a)
print("No. of dimension :",a.ndim)

10
No. of dimension : 0


In [79]:
b=np.array([10,12,13])  # this is called vector
print(b)
print("No. of dimension :",b.ndim)

[10 12 13]
No. of dimension : 1


In [80]:
c=np.array([[1,2,3],[2,3,4]])  # this is called multidimensional array or matrix
print(c)
print("No. of dimension :",c.ndim)

[[1 2 3]
 [2 3 4]]
No. of dimension : 2


In [81]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(c)
print("No. of dimension :",c.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]
No. of dimension : 3


In [86]:
np.random.randint(1,10,(2,2,3))

array([[[6, 6, 2],
        [9, 8, 2]],

       [[9, 5, 1],
        [2, 9, 2]]])

In [100]:
# aadharcard=([np.array(np.random.randint(111111111111,999999999999),dtype=np.int64) for i in range(20)])

In [103]:
print([np.random.randint(1000000,999944444) for i in range(20)])

[448095776, 74425898, 959883723, 296948751, 560405256, 171264515, 308075734, 868344751, 251253625, 914945716, 381570913, 696548200, 863551220, 327689381, 783536843, 839915604, 71782402, 221919916, 915388340, 551049296]


In [112]:
np.random.randint(1,100,50)

array([14, 96, 31, 22, 65, 98, 96,  5, 25, 41, 55, 34, 34, 39, 36, 56, 70,
       56, 97, 45, 72, 18, 13, 43, 26, 83, 36, 19, 64, 82, 73, 17, 38, 35,
       23, 78, 95, 98, 13, 16, 20, 34, 34, 26, 13, 10, 97, 75, 19, 48])

In [120]:
np.round(np.random.uniform(1,100,50),decimals=2)

array([28.46, 25.65, 57.46, 19.06, 38.16, 63.98, 39.18, 25.99, 24.06,
        3.33, 23.48, 80.62, 90.25, 60.36, 41.54, 71.59, 65.89, 51.1 ,
       72.97, 31.52, 43.48,  6.99, 91.56, 44.73, 69.62, 81.67, 90.52,
       38.21, 44.44, 55.61, 18.05, 23.74, 75.12, 38.13, 61.56, 66.23,
        1.67, 63.44, 95.36, 49.07, 31.75, 94.2 , 71.08, 75.77, 35.38,
       70.37, 53.17, 31.53, 22.09, 66.35])

In [119]:
np.round(np.array(np.random.randint(1,100,50,), dtype=np.float64))

array([12., 27.,  7., 51., 68., 68., 74., 36., 84., 27., 56., 15., 78.,
       49., 52., 60., 99.,  1., 56., 20., 46., 28., 54., 58., 51., 11.,
       11., 69.,  7., 78., 97., 21., 48., 17., 80., 96., 89., 21., 23.,
       48., 86., 94., 69., 39., 93., 68., 67., 62., 53., 78.])